name: Telegram Heartbeat

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  heartbeat:
    runs-on: ubuntu-latest

    steps:
      - name: Send heartbeat
        run: |
          curl -X POST \
          https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="💓 GitHub Actions heartbeat $(date)"
